server:
  port: 9527

jwt:
  secret: ntzvtcNo+hjeo4br7lk5VVYfzxN7fya465deA8+dfqw=

spring:
  config:
    import:
      - optional:nacos:application.yml
      # 显式导入配置，还记得吗，nacos中的规则
      - optional:nacos:menu-authorities.yaml
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  main:
    web-application-type: reactive
  data:
    redis:
      host: 118.31.120.30
      port: 6379
      password: 123456
  application:
    name: cloud-gateway #以微服务注册进consul或nacos服务列表内
  cloud:
    nacos:
      discovery:
        server-addr:  localhost:8848
      config:
        file-extension: yaml
        group: DEFAULT_GROUP
        namespace: public
        server-addr:  localhost:8848
        refreshable-data-ids: menu-authorities.yaml
    gateway:
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:5173/"
              - "http://127.0.0.1:5173/"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
      routes:
        - id: cloud-price-consumer #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-price-consumer           #匹配后提供服务的路由地址
          predicates:
#            - Path=/test/**            # 断言，路径相匹配的进行路由
            - Path=/draw/**            # 断言，路径相匹配的进行路由
          filters:
            - Auth
        - id: cloud-user
          uri: lb://cloud-user
          predicates:
            - Path=/**